name: guru_nest
description: A Flutter learning platform with Supabase backend.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  device_preview: ^1.1.0 # or latest version
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.3.3
  sizer: ^2.0.15
  shared_preferences: ^2.2.2
  iconly: ^1.0.1
  image_picker: ^1.0.7
  fl_chart: ^1.0.0
  file_picker: ^10.1.9
  path: ^1.8.3
  path_provider: ^2.0.15
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  http: ^1.2.0
  flutter_pdfview: ^1.3.2
  video_player: ^2.8.2
  chewie: ^1.7.4
  dio: ^5.4.1
  # device_preview: ^1.3.1
#  screen_protector: ^2.0.0

  #  flutter_windowmanager: ^0.2.0
  screen_protector: ^1.4.2+1
  pay: ^1.1.0
  upi_pay: ^1.1.0
  flutter_upi_india: 0.0.6
  razorpay_flutter: ^1.3.6
  android_intent_plus: 5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  go_router: ^13.2.2 # ✅ or latest version

  json_serializable: ^6.7.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gpay_payment_config.json

